/** @format */

import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/src/lib/utils';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { ThemeProvider } from '../components/theme-provider';

const interHeading = Inter({ subsets: ['latin'], variable: '--font-heading' });

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        geist.variable,
        interHeading.variable,
      )}
    >
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className='flex-1 flex justify-center'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
