/** @format */

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Yogesh Dhuri',
    template: '%s | Yogesh Dhuri',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className='bg-amber-400'>dashHeader</header>
      <main>{children}</main>
      <footer className='bg-red-700'>dashFooter</footer>
    </>
  );
}
